# Placeholder file templates for Terraform module scaffold
$script:TemplateVersionsTf = @'
terraform {
  required_version = "~>1.9, < 2.0"

  required_providers {
    azurerm = {
      ## Azure resource manager
      source  = "hashicorp/azurerm"
      version = "~>4.0, < 5.0"
    }
    azuread = {
      ## Azure AD (Entra ID)
      source  = "hashicorp/azuread"
      version = "~>3.0, < 4.0"
    }
    msgraph = {
      ## Microsoft Graph - eventual replacement for azuread
      source  = "microsoft/msgraph"
      version = "~> 0.0, < 1.0"
    }
    azapi = {
      ## use for Azure resources that are not directly support by azurerm or azuread providers
      source  = "azure/azapi"
      version = "~>2.0, < 3.0"
    }
    #powerplatform = {
    ## Power Platform
    #  source  = "microsoft/power-platform"
    #  version = "~>4.0, < 5.0"
    #}
    random = {
      ## Random
      source  = "hashicorp/random"
      version = "~>3.0, < 4.0"
    }
    acme = {
      ## ACME for Let's Encrypt
      source  = "vancluever/acme"
      version = "~>2.0, < 3.0"
    }
  }
}
'@

$script:TemplateExampleVersionsTf = @'
terraform {
  required_version = ">= 1.3.0"
}
'@

$script:TemplateExampleMainTf = @'
module "example" {
  source = "../../"
}
'@

$script:TemplateTerraformDocsYml = @'
formatter: "markdown table"

header-from: "_header.md"
footer-from: "_footer.md"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  <!-- Code generated by terraform-docs. DO NOT EDIT. -->
  {{ .Header }}

  <!-- markdownlint-disable MD033 -->
  {{ .Requirements }}

  {{ .Resources }}

  <!-- markdownlint-disable MD013 -->
  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Modules }}

  {{ .Footer }}

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
'@

$script:TemplateGitignore = @'
# Local .terraform directories
**/.terraform/*

# .tfstate files
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Exclude all .tfvars files, which are likely to contain sensitive data, such as
# password, private keys, and other secrets. These should not be part of version 
# control as they are data points which are potentially sensitive and subject 
# to change depending on the environment.
*.tfvars
*.tfvars.json

# Ignore override files as they are usually used to override resources locally and so
# are not checked in
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Include override files you do wish to add to version control using negated pattern
# !example_override.tf

# Include tfplan files to ignore the plan output of command: terraform plan -out=tfplan
# example: *tfplan*

# Ignore CLI configuration files
.terraformrc
terraform.rc

# Ignore lock files
.terraform.lock.hcl
*tfplan*
README-generated.md
avm.tflint.hcl
avm.tflint.merged.hcl
avm.tflint_example.hcl
avm.tflint_example.merged.hcl
avmmakefile
*.md.tmp
.DS_Store
avm.tflint_module.hcl
avm.tflint_module.merged.hcl
examples/*/policy
*.mptfbackup
.avm/managed-files.json
'@

$script:TemplateEditorConfig = @'
# EditorConfig: Windows dev host, Azure Container Apps (.NET Aspire), WSL/Linux targets
root = true

# ---- Global defaults ----
[*]
charset = utf-8
indent_style = space
indent_size = 4
end_of_line = crlf
insert_final_newline = true
trim_trailing_whitespace = true
max_line_length = off

# ---- C# / .NET Aspire / ACA projects ----
[*.{cs,csx}]
indent_size = 4
end_of_line = crlf
csharp_new_line_before_open_brace = all
csharp_indent_case_contents = true
csharp_prefer_braces = true
dotnet_sort_system_directives_first = true
dotnet_style_qualification_for_field = false
dotnet_style_qualification_for_property = false
dotnet_style_qualification_for_method = false
dotnet_style_predefined_type_for_locals_parameters_members = true
csharp_style_var_for_built_in_types = false
csharp_style_var_when_type_is_apparent = true
csharp_style_namespace_declarations = file_scoped

[*.{csproj,props,targets}]
indent_size = 2
end_of_line = crlf

# ---- PowerShell (WSL provisioning, Az automation) ----
[*.{ps1,psm1,psd1}]
indent_size = 4
end_of_line = crlf
charset = utf-8-bom

# ---- Terraform (AzureRM / AzureAD / AzApi) ----
[*.{tf,tfvars}]
indent_size = 2
end_of_line = lf
insert_final_newline = true

[*.tfstate]
insert_final_newline = false

# ---- Bash / WSL provisioning scripts ----
[*.sh]
indent_size = 2
end_of_line = lf
insert_final_newline = true

# ---- Dockerfiles (ACA container builds) ----
[{Dockerfile,Dockerfile.*,*.dockerfile}]
indent_size = 4
end_of_line = lf

# ---- YAML (pipelines, ACA revisions, k8s-adjacent manifests) ----
[*.{yml,yaml}]
indent_size = 2
end_of_line = lf

# ---- JSON / Bicep-adjacent / ARM ----
[*.{json,jsonc,bicep}]
indent_size = 2
end_of_line = lf

# ---- Markdown docs ----
[*.md]
indent_size = 2
trim_trailing_whitespace = false
end_of_line = lf

# ---- Batch files (rare, but Windows-native) ----
[*.{cmd,bat}]
end_of_line = crlf

# ---- Makefiles require literal tabs ----
[Makefile]
indent_style = tab
end_of_line = lf
'@

$script:TemplateGitAttributes = @'
# Default: normalize all text files and prefer LF in the repo
* text=auto eol=lf

# Windows batch/cmd usually expects CRLF
*.bat  text eol=crlf
*.cmd  text eol=crlf
*.ps1xml text eol=lf

# PowerShell  usually expects CRLF
*.ps1  text eol=crlf
*.psm1 text eol=crlf
*.psd1 text eol=crlf

# Shell / scripts
*.sh   text eol=lf
*.bash text eol=lf
*.zsh  text eol=lf

# IaC / config
*.tf        text eol=lf
*.tfvars    text eol=lf
*.hcl       text eol=lf
*.yml       text eol=lf
*.yaml      text eol=lf
*.json      text eol=lf
*.md        text eol=lf
*.txt       text eol=lf

# Binary (never touch line endings)
*.png  binary
*.jpg  binary
*.jpeg binary
*.gif  binary
*.pdf  binary
*.zip  binary
*.7z   binary
*.exe  binary
*.dll  binary
'@

$script:Dependabot = @'
---
# Dependabot version updates
#
# Dependabot security updates (CVE-driven) are enabled at the repository level
# via Terraform; this file enables proactive *version* updates for pinned
# provider versions.
#
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  # Terraform providers in the root module, examples, and any submodules.
  - package-ecosystem: terraform
    directories:
      - "/"
      - "/examples/**"
      - "/modules/**"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Australia/Melbourne
    groups:
      terraform:
        patterns:
          - "*"
    labels:
      - "Language: Terraform :globe_with_meridians:"
    commit-message:
      prefix: chore
      include: scope
'@

$script:TemplatePullRequest = @'
<!-- Pull Request Template -->
## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## AI Assistance Disclosure
- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

> [!NOTE]
> If this PR changes meaningfully during the course of review please update the title and description as required.

'@

$script:TemplateVsCodeSettings = @'
{
    "files.autoSave": "afterDelay",
    "editor.defaultFormatter": "GitHub.copilot-chat",
    "editor.fontFamily": "FiraCode",
    "[powershell]": {
        "editor.defaultFormatter": "ms-vscode.powershell"
    },
    "[github-actions-workflow]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[terraform]": {
        "editor.defaultFormatter": "hashicorp.terraform"
    }
}
'@

$script:TemplateVsCodeExtensions = @'
{
  "recommendations": [
    "EditorConfig.EditorConfig",
    "hashicorp.terraform",
    "ms-azuretools.vscode-azureterraform"
  ]
}
'@

$script:TemplateWelcome = @'
# Welcome to Your Terraform Module

This repository was scaffolded to help you build and publish a reusable Terraform module with a clean structure and CI-ready defaults.

## What's Included

- Module entry files: `main.tf`, `variables.tf`, `outputs.tf`, `versions.tf`
- Examples: `examples/basic` and `examples/complete`
- Validation and docs workflow in `.github/workflows`
- Formatting and editor standards via `.editorconfig` and `.gitattributes`

## Quick Start

1. Review and update module inputs in `variables.tf`
2. Implement resources in `main.tf`
3. Add outputs in `outputs.tf`
4. Test examples from `examples/basic` and `examples/complete`

## Useful Commands

```bash
terraform fmt -check -recursive
terraform init
terraform validate
```

## Next Steps

- Update GitHub secrets for CI:
  - `AZURE_CLIENT_ID`
  - `AZURE_TENANT_ID`
  - `AZURE_SUBSCRIPTION_ID`
- Create a release tag when ready to publish
- Keep README docs in sync with `terraform-docs`

Happy building.
'@

$script:TemplateClaude = @'
# Project

This is a Terraform module scaffolded repository.

# Commands
- Terrafrom Formating: `terrafrom fmt -check -recursive`

# Code Style
- Use 2-space indentation
- Enusre appropriate terrafrom output variables are defined.
- Use Terraform Azure Verified Modules in preference to the azurerm, msgraph and azapi providers.
- Avoid use of the Azure azuread if possible.
'@

$script:TemplateDevContainer = @'
{
  "$schema": "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json",
  "name": "Azure Terraform",

  // Use a minimal base image — dotnet is installed via the feature below
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu-24.04",

  "remoteUser": "vscode",

  "features": {
    "ghcr.io/devcontainers/features/github-cli:1": {
      "version": "latest"
    },
    // docker-outside-of-docker is preferred in Codespaces (shares host socket, lower overhead)
    "ghcr.io/devcontainers/features/docker-outside-of-docker:1": {},
    "ghcr.io/azure/azure-dev/azd:0": {},
    "ghcr.io/devcontainers/features/azure-cli:1": {
      "version": "latest"
    },
    "ghcr.io/devcontainers/features/terraform:1": {
      "version": "latest",
      "installTFsec": "false",
      "installTerraformDocs": "true"
    },
    "ghcr.io/devcontainers/features/node:1": {
      "version": "lts"
    },
    "ghcr.io/devcontainers/features/powershell:1": {
      "version": "latest"
    },
    "ghcr.io/devcontainers/features/dotnet:2": {
      "version": "latest",
      "additionalVersions": "9.0"
    }
  },

  "mounts": [
    {
      "type": "volume",
      "source": "x509stores",
      "target": "/home/vscode/.dotnet/corefx/cryptography/x509stores"
    },
    {
      // Works on Linux/macOS (HOME set) and Windows (USERPROFILE set); one will be empty
      "type": "bind",
      "source": "${localEnv:HOME}${localEnv:USERPROFILE}/.azure",
      "target": "/home/vscode/.azure"
    }
  ],

  // These must be set as Codespaces secrets or local environment variables
  // ${{ secrets.* }} syntax is NOT interpolated in devcontainer.json
  "containerEnv": {
    "AZURE_CLIENT_ID":       "${localEnv:AZURE_CLIENT_ID}",
    "AZURE_TENANT_ID":       "${localEnv:AZURE_TENANT_ID}",
    "AZURE_SUBSCRIPTION_ID": "${localEnv:AZURE_SUBSCRIPTION_ID}"
  },

  "customizations": {
    "codespaces": {
      "openFiles": ["WELCOME.md"]
    },
    "vscode": {
      "settings": {
        "[terraform]": {
          "editor.defaultFormatter": "hashicorp.terraform",
          "editor.formatOnSave": true
        },
        "[tfvars]": {
          "editor.defaultFormatter": "hashicorp.terraform"
        },
        "editor.bracketPairColorization.enabled": true,
        "editor.codeActionsOnSave": {
          "source.fixAll": "explicit"
        },
        "editor.formatOnPaste": true,
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.guides.bracketPairs": "active",
        "editor.inlineSuggest.enabled": true,
        "editor.linkedEditing": true,
        "editor.multiCursorModifier": "alt",
        "editor.renderControlCharacters": true,
        "editor.renderWhitespace": "all",
        "editor.rulers": [
          { "color": "#A5FF90", "column": 80  },
          { "color": "#FF628C", "column": 100 }
        ],
        "editor.stickyScroll.enabled": true,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "on",
        "editor.tabSize": 2,
        "extensions.ignoreRecommendations": true,
        "files.associations": {
          "*.sh.tmpl": "shellscript"
        },
        "files.eol": "\n",
        "files.autoGuessEncoding": false,
        "files.trimTrailingWhitespace": true,
        "json.validate.enable": true,
        "markdown.updateLinksOnFileMove.enabled": "always",
        "terraform.languageServer": {
          "enabled": true
        },
        "security.workspace.trust.enabled": false,
        "redhat.telemetry.enabled": false
      },
      "extensions": [
        "GitHub.copilot",
        "GitHub.copilot-chat",
        "GitHub.vscode-github-actions",
        "HashiCorp.terraform",
        "ms-azuretools.vscode-azureappservice",
        "ms-azuretools.vscode-azurefunctions",
        "ms-azuretools.vscode-azureresourcegroups",
        "ms-azuretools.vscode-azureterraform",
        "ms-dotnettools.csharp",
        "ms-dotnettools.vscode-dotnet-runtime",
        "ms-vscode.azure-account",
        "ms-vscode.azurecli",
        "ms-vscode.powershell",
        "redhat.vscode-yaml",
        "timonwong.shellcheck"
      ],
      "unwantedRecommendations": [
        "eamodio.gitlens"
      ]
    }
  },

  // Verify tool versions and install Az PowerShell module
  "postCreateCommand": "terraform --version && terraform-docs --version && azd version",

  // Safe: fetch only, no destructive reset
  "postStartCommand": "git fetch origin"
}
'@
##   'onCreateCommand': 'bash .devcontainer/scripts/setup-dotnet-dev-cert.sh',
##  && azd version && pwsh -Command 'Install-Module Az -Scope CurrentUser -Force -AcceptLicense *> $null && Write-Host \"Az PowerShell module installed\"'

$script:TemplateCiWorkflow = @'
name: Terraform-Modules-Docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        continue-on-error: true

      - uses: hashicorp/setup-terraform@v4

      - name: terraform fmt
        run: terraform fmt -check -recursive

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
'@

$script:TemplatePerimterWorkflow = @'
name: Setup Azure Network Security Perimeter (NSP)

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Terraform - Plan/Apply Initial"]
    types: [completed]

permissions:
  contents: read
  actions: read

jobs:
  consume-outputs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Exit 
        shell: bash
        run: |
          exit 0

      - name: Checkout
        if: ${{ false }}
        uses: actions/checkout@v7

      - name: Download artifact from triggering run
        if: ${{ true }}
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          name: tfplan-outputs-${{ matrix.runs-on }}.json
          path: ./downloaded-artifact

      - name: Read JSON output
        if: ${{ true }}
        shell: bash
        run: |
          cat ./downloaded-artifact/tfplan-output-values-ubuntu-latest.json
          ACR_ID=$(jq -r '.acr_id' ./downloaded-artifact/tfplan-output-values-ubuntu-latest.json)
          SECURITY_PERIMETER_ID=$(jq -r '.security_perimeter_id' ./downloaded-artifact/tfplan-output-values-ubuntu-latest.json)
          SECURITY_PERIMETER_RESOURCES=$(jq -r '.security_perimeter_resources' ./downloaded-artifact/tfplan-output-values-ubuntu-latest.json)
          NETWORK_SECURITY_PERIMETER_PROFILE_ID=$(jq -r '.network_security_perimeter_profile_id' ./downloaded-artifact/tfplan-output-values-ubuntu-latest.json)
          echo "ACR ID from env file                               : $ACR_ID"
          echo "SECURITY_PERIMETER_ID from env file                : $SECURITY_PERIMETER_ID"
          echo "SECURITY_PERIMETER_RESOURCES from env file         : $SECURITY_PERIMETER_RESOURCES"
          echo "NETWORK_SECURITY_PERIMETER_PROFILE_ID from env file: $NETWORK_SECURITY_PERIMETER_PROFILE_ID"
          #echo "Resources from env file: $SECURITY_PERIMETER_RESOURCES"
          #echo "NETWORK_SECURITY_PERIMETER_PROFILE_ID from env file: $NETWORK_SECURITY_PERIMETER_PROFILE_ID"
          #echo "SECURITY_PERIMETER_ID=$SECURITY_PERIMETER_ID" >> $GITHUB_ENV
          #echo "SECURITY_PERIMETER_RESOURCES=$SECURITY_PERIMETER_RESOURCES" >> $GITHUB_ENV
          #echo "NETWORK_SECURITY_PERIMETER_PROFILE_ID=$NETWORK_SECURITY_PERIMETER_PROFILE_ID"
          exit 0

      - name: Read ENV output
        if: ${{ false }}
        shell: bash
        run: |
          source ./downloaded-artifact/tfplan-outputs-ubuntu-latest.env
          echo "ID from env file: $security_perimeter_id"
          echo "ACR ID from env file: $acr_id"
          echo "Resources from env file: $security_perimeter_resources"

      - name: Security Perimeter Association
        #-var.security_perimeter_resources
        #-var.network_security_perimeter_profile_id
'@

$script:TemplateReleaseWorkflow = @'
name: Module Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Mark as pre-release"
        required: false
        type: boolean
        default: false
      draft:
        description: "Create as draft"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # full history for release notes generation

      - name: Compute next minor version
        run: |
          latest_tag="$(git tag --list 'v*' --sort=-version:refname | head -n 1)"

          if [[ -z "$latest_tag" ]]; then
            version="v0.1.0"
          elif [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            version="v${BASH_REMATCH[1]}.$((BASH_REMATCH[2] + 1)).0"
          else
            echo "ERROR: Latest tag '$latest_tag' is not a valid vX.Y.Z version"
            exit 1
          fi

          echo "VERSION=$version" >> "$GITHUB_ENV"
          echo "Computed release version: $version"

      - name: Check tag does not already exist
        run: |
          if git rev-parse "$VERSION" &>/dev/null; then
            echo "ERROR: Tag $VERSION already exists"
            exit 1
          fi

      - name: Create release
        run: |
          gh release create "$VERSION" \
            --title "$VERSION" \
            --generate-notes \
            --target "${{ github.ref_name }}" \
            ${{ inputs.prerelease && '--prerelease' || '--latest' }} \
            ${{ inputs.draft && '--draft' || '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Write release summary
        run: |
          release_url="$(gh release view "$VERSION" --json url --jq '.url')"

          {
            echo "## Module release created"
            echo
            echo "| Detail | Value |"
            echo "| --- | --- |"
            echo "| Version | [$VERSION](${release_url}) |"
            echo "| Target branch | \`${{ github.ref_name }}\` |"
            echo "| Commit | \`${{ github.sha }}\` |"
            echo "| Pre-release | \`${{ inputs.prerelease }}\` |"
            echo "| Draft | \`${{ inputs.draft }}\` |"
            echo "| Triggered by | @${{ github.actor }} |"
          } >> "$GITHUB_STEP_SUMMARY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
'@

function New-TerraformModuleRepo {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory = $true, HelpMessage = 'Name of the Terraform module')]
    [string]$ModuleName,

    [string]$Provider = 'azurerm',

    [Parameter(Mandatory = $true, HelpMessage = 'Description of the module for the GitHub repository')]
    [string]$Description,

    [string]$Owner = 'webstean'
  )

  $repoName = "terraform-$Provider-$ModuleName"
  Write-Host "Creating Terraform module repository: '$repoName'"

  if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    throw 'GitHub CLI (gh) not found. Install via: winget install GitHub.cli'
  }

  if (-not (gh auth status 2>&1 | Select-String 'Logged in')) {
    throw 'Not authenticated. Run: gh auth login'
  }

  if (-not $Owner) {
    $Owner = (gh api user | ConvertFrom-Json).login
  }
  Write-Host "Repository owner is: '$Owner'"

  Write-Host "Checking (with view)....'${Owner}/$repoName'"
  if (gh repo view ${Owner}/${repoName} 2>$null) {
    Write-Host "'gh repo delete $Owner/$repoName --yes'"
    Write-Host "'gh auth refresh -s delete_repo'"
    throw 'Repository directory already exists.'
  }
  $desc = if ($Description) { $Description } else { "Terraform module for $ModuleName with provider $Provider" }
  if (-not (gh repo create $Owner/$repoName --description "$Description" --public )) {
    throw 'Failed to create repository.'
  }

  $repoPath = Join-Path (Get-Location) $repoName
  if (Test-Path $repoPath) { 
    throw "Repository path '$repoPath' already exists."
  }
  New-Item -ItemType Directory -Path $repoPath -Force -ErrorAction SilentlyContinue | Out-Null
  Write-Host "Repository path is: '$repoPath'"
  if (-not (Test-Path $repoPath)) { 
    throw "Repository path '$repoPath' does not exist."
  }
  Push-Location $repoPath -ErrorAction SilentlyContinue

  try {
    $dirs = @(
      'modules',
      'examples/complete',
      'examples/basic',
      '.vscode',
      '.devcontainer',
      'tests'
    )
    foreach ($dir in $dirs) {
      New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    $script:TemplateVersionsTf | Set-Content 'versions.tf'
    '# Input variables' | Set-Content 'variables.tf'
    '# Resources' | Set-Content 'main.tf'
    '# Outputs' | Set-Content 'outputs.tf'
    $script:TemplateClaude | Set-Content 'CLAUDE.md'

    $script:TemplateExampleMainTf | Set-Content 'examples/basic/main.tf'
    $script:TemplateExampleVersionsTf | Set-Content 'examples/basic/versions.tf'

    '' | Set-Content 'examples/basic/variables.tf'
    '' | Set-Content 'examples/basic/outputs.tf'
    '' | Set-Content 'examples/basic/README.md'

    '## $repoName' | Set-Content '_header.md'
    '- (c) Andrew Webster <webstean@gmail.com>' | Set-Content '_footer.md'
  

    Copy-Item 'examples/basic/main.tf' 'examples/complete/main.tf'
    Copy-Item 'examples/basic/versions.tf' 'examples/complete/versions.tf'
    Copy-Item 'examples/basic/variables.tf' 'examples/complete/variables.tf'
    Copy-Item 'examples/basic/outputs.tf' 'examples/complete/outputs.tf'
    Copy-Item 'examples/basic/README.md' 'examples/complete/README.md'
    
    '# go test -v -timeout 30m' | Set-Content 'tests/main_test.go'

    $script:TemplateTerraformDocsYml | Set-Content '.terraform-docs.yml'

    $script:TemplateWelcome | Set-Content 'WELCOME.md'
    $script:TemplateGitignore | Set-Content '.gitignore'
    $script:TemplateEditorConfig | Set-Content '.editorconfig'
    $script:TemplateGitAttributes | Set-Content '.gitattributes'
    $script:TemplateVsCodeSettings | Set-Content '.vscode/settings.json'
    $script:TemplateVsCodeExtensions | Set-Content '.vscode/extensions.json'
    $script:TemplateDevContainer | Set-Content '.devcontainer/devcontainer.json'

    @"
# terraform-$Provider-$ModuleName

$desc

## Usage

``````hcl
module "$ModuleName" {
  source  = "$Owner/$ModuleName/$Provider"
  version = "~> 1.0"
}
``````

<!-- BEGIN_TF_DOCS -->
<!-- END_TF_DOCS -->

## Examples

- [Basic](./examples/basic)
- [Complete](./examples/complete)

## Contributing

Contributions welcome. Please open an issue or PR.

## License

MIT
"@ | Set-Content 'README.md'

    @"
# MIT License

Copyright (c) 2025-$(Get-Date -Format yyyy) Andrew Webster

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"@ | Set-Content 'LICENSE'

    Get-Location
    New-Item -ItemType Directory -Path '.github/workflows' -Force | Out-Null
    $script:TemplateCiWorkflow | Set-Content '.github/workflows/ci-terraform-docs.yml'
    $script:TemplateReleaseWorkflow | Set-Content '.github/workflows/release.yml'
    $script:Dependabot | Set-Content '.github/dependabot.yml'
    $script:TemplatePullRequest | Set-Content '.github/pull_request_template.md'

    git init
    git add -A
    git commit -m 'initial commit'
    git branch -M main
    git remote add origin https://github.com/$Owner/${repoName}.git
    git push -u origin main
    gh label create 'Language: Terraform :globe_with_meridians:' --color '5C4EE5' --repo "$Owner/$repoName"

    git tag v0.1.0
    git push origin v0.1.0

    gh repo edit "$Owner/$repoName" --homepage "https://registry.terraform.io/modules/$Owner/$ModuleName/$Provider"

    Write-Host 'Creating placeholder secrets...'
    @{
      AZURE_CLIENT_ID       = 'REPLACE_ME'
      AZURE_TENANT_ID       = 'REPLACE_ME'
      AZURE_SUBSCRIPTION_ID = 'REPLACE_ME'
    }.GetEnumerator() | ForEach-Object {
      gh secret set $_.Key --body $_.Value --repo "$Owner/$repoName"
    }

    Write-Host ''
    Write-Host "Repository : '$Owner/$repoName'"
    Write-Host "Path       : '$repoPath'"
    Write-Host ''
    Write-Host 'GitHub Secrets created (Optional, update with real values, if required):'
    Write-Host ' AZURE_CLIENT_ID'
    Write-Host ' AZURE_TENANT_ID'
    Write-Host ' AZURE_SUBSCRIPTION_ID'
    Write-Host ''
    Write-Host ' Requirements checklist:'
    Write-Host " [x] Repo named '$repoPath'"
    Write-Host ' [x] Public repository'
    Write-Host ' [x] main.tf / variables.tf / outputs.tf present'
    Write-Host ' [x] v0.1.0 tag pushed'
    Write-Host " [ ] GitHub OAuth app must be authorized for '$Owner' org/account"
    Write-Host ' https://github.com/settings/connections/applications/b0e1b0f5f7ca9fb13c7d'
    Write-Host ''
    Write-Host ' Once published, module source for Terraform will be:'
    Write-Host ''
    Write-Host "  module '$ModuleName' {"
    Write-Host "    source           = '$Owner/$ModuleName/$Provider'"
    Write-Host "    version          = '~>0.0, < 1.0'"
    Write-Host '    enable_telemetry = var.enable_telemetry'
    Write-Host ''
    Write-Host ' ...'
    Write-Host ''
    Write-Host '  }'
    Write-Host ''
    Write-Host 'Terraform Registry Publishing:'
    Write-Host ' 1. Sign in at 'https://registry.terraform.io' with your GitHub account'
    Write-Host " 2. Click 'Publish' > 'Module'"
    Write-Host " 3. Select the '$repoName' repository"
    Write-Host ' 4. Confirm — registry will detect versions from git tags (v0.1.0 already pushed)'
    Write-Host ''
    Write-Host 'Nothing will appear, until you do a release'
    Write-Host 'gh release create v0.99 --generate-notes --target main'
    Write-Host ''

    # Final script output for automation/consumers
    Write-Output ([pscustomobject]@{
        Repo       = "https://github.com/$Owner/$repoName"
        RepoOwner  = $Owner
        RepoName   = $repoName
        ModuleName = $ModuleName
      })

  } finally {
    Pop-Location
  }
}
New-TerraformModuleRepo
